//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.26 at 08:31:12 AM CET 
//


package com.poverenik.poverenik.model.resenja;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.resenja package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TipDogadjajDatumIzvrsenja_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "datum_izvrsenja");
    private final static QName _TipDogadjajDatumPodnetogZahteva_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "datum_podnetog_zahteva");
    private final static QName _TipDogadjajZrtva_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "zrtva");
    private final static QName _TipDogadjajRazlogZahtevaZaInformacijeOdJavnogZnacaja_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "razlog_zahteva_za_informacije_od_javnog_znacaja");
    private final static QName _TipDogadjajDatumZahteva_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "datum_zahteva");
    private final static QName _TipDogadjajDatumObavestenja_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "datum_obavestenja");
    private final static QName _TipDogadjajIzvrsenjeResenja_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "izvrsenje_resenja");
    private final static QName _TipDogadjajOptuzeni_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "optuzeni");
    private final static QName _TipPoverenikImePoverenika_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "ime_poverenika");
    private final static QName _TipTrazenjeOdgovoraOdStraneOptuzenogDatumOdgovoraNaZalbu_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "datum_odgovora_na_zalbu");
    private final static QName _TipTrazenjeOdgovoraOdStraneOptuzenogDatumAkcijePoverenika_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "datum_akcije_poverenika");
    private final static QName _TipTrazenjeOdgovoraOdStraneOptuzenogStaSeTrazilo_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "sta_se_trazilo");
    private final static QName _TipTrazenjeOdgovoraOdStraneOptuzenogZakon_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "zakon");
    private final static QName _TipUpustvoRokZaPokretanjeUpravnogSpora_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "rok_za_pokretanje_upravnog_spora");
    private final static QName _TipUpustvoTaksaTuzbe_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "taksa_tuzbe");
    private final static QName _TipResenjeZalbeRokTrajanjaMoraIzvrsiResenje_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "rok_trajanja_mora_izvrsi_resenje");
    private final static QName _TipResenjeZalbeDokumentKojiSeTrazi_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "dokument_koji_se_trazi");
    private final static QName _TipResenjeZalbeOperacijeKojeOptuzeniMoraDaIzvrsi_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "operacije_koje_optuzeni_mora_da_izvrsi");
    private final static QName _TipResenjeZalbeRokTrajanjaProvera_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "rok_trajanja_provera");
    private final static QName _TipOpisZalbeDatumIzbora_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "datum_izbora");
    private final static QName _TipOpisZalbeSuBr_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "su.br.");
    private final static QName _TipOpisZalbeDatumPokretanja_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "datum_pokretanja");
    private final static QName _TipRazlogZahtevaZaInformacijeOdJavnogZnacajaInformacija_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "informacija");
    private final static QName _TipOdgovorNaDogadjajLokacijaSmrti_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "lokacija_smrti");
    private final static QName _TipOdgovorNaDogadjajDatumSmrtiPolicija_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "datum_smrti_policija");
    private final static QName _TipOdgovorNaDogadjajRokOdPrijemaZahteva_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "rok_od_prijema_zahteva");
    private final static QName _TipOdgovorNaDogadjajDatumSmrti_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "datum_smrti");
    private final static QName _TipOdgovorNaDogadjajBrojObavestenja_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "broj_obavestenja");
    private final static QName _TipOdgovorNaDogadjajDatumIzlaskaInspektora_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "datum_izlaska_inspektora");
    private final static QName _TipOdgovorNaDogadjajRokOObavestenjuDaLiPosedujeInformacije_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "rok_o_obavestenju_da_li_poseduje_informacije");
    private final static QName _TipRazlogPodnosenjaZalbeDatumDoKadaMoraDaSeIzvrsi_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "datum_do_kada_mora_da_se_izvrsi");
    private final static QName _TipRazlogPodnosenjaZalbeDatumZalbe_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "datum_zalbe");
    private final static QName _TipOperacijeKojeOptuzeniMoraDaIzvrsiPrivatneInformacijeKojeOptuzeniMoraDaZastiti_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "privatne_informacije_koje_optuzeni_mora_da_zastiti");
    private final static QName _ResenjeFusnota_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "fusnota");
    private final static QName _ResenjePoverenik_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "poverenik");
    private final static QName _ResenjePodnaslov_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "podnaslov");
    private final static QName _ResenjeResenjeZalbe_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "resenje_zalbe");
    private final static QName _ResenjeNaslov_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "naslov");
    private final static QName _ResenjeDesno_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "desno");
    private final static QName _ResenjeLevo_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "levo");
    private final static QName _ResenjeObrazlozenjaZalbe_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "obrazlozenja_zalbe");
    private final static QName _ResenjeOpisZalbe_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "opis_zalbe");
    private final static QName _TipZakonClan_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "clan");
    private final static QName _TipZakonNazivZakona_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "naziv_zakona");
    private final static QName _TipZakonTacka_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "tacka");
    private final static QName _TipZakonNazivSluzbenogGlasnika_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "naziv_sluzbenog_glasnika");
    private final static QName _TipZakonStav_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "stav");
    private final static QName _TipZakonBrojSl_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "broj_sl.");
    private final static QName _TipOptuzeniSedisteOptuzenog_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "sediste_optuzenog");
    private final static QName _TipOptuzeniNazivOptuzenog_QNAME = new QName("http://www.ftn.uns.ac.rs/resenja", "naziv_optuzenog");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.resenja
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TipRazlogZahtevaZaInformacijeOdJavnogZnacaja }
     * 
     */
    public TipRazlogZahtevaZaInformacijeOdJavnogZnacaja createTipRazlogZahtevaZaInformacijeOdJavnogZnacaja() {
        return new TipRazlogZahtevaZaInformacijeOdJavnogZnacaja();
    }

    /**
     * Create an instance of {@link TipZakon }
     * 
     */
    public TipZakon createTipZakon() {
        return new TipZakon();
    }

    /**
     * Create an instance of {@link TipOperacijeKojeOptuzeniMoraDaIzvrsi }
     * 
     */
    public TipOperacijeKojeOptuzeniMoraDaIzvrsi createTipOperacijeKojeOptuzeniMoraDaIzvrsi() {
        return new TipOperacijeKojeOptuzeniMoraDaIzvrsi();
    }

    /**
     * Create an instance of {@link Resenje }
     * 
     */
    public Resenje createResenje() {
        return new Resenje();
    }

    /**
     * Create an instance of {@link TipLevo }
     * 
     */
    public TipLevo createTipLevo() {
        return new TipLevo();
    }

    /**
     * Create an instance of {@link TipDesno }
     * 
     */
    public TipDesno createTipDesno() {
        return new TipDesno();
    }

    /**
     * Create an instance of {@link TipOpisZalbe }
     * 
     */
    public TipOpisZalbe createTipOpisZalbe() {
        return new TipOpisZalbe();
    }

    /**
     * Create an instance of {@link TipResenjeZalbe }
     * 
     */
    public TipResenjeZalbe createTipResenjeZalbe() {
        return new TipResenjeZalbe();
    }

    /**
     * Create an instance of {@link TipObrazlozenjaZalbe }
     * 
     */
    public TipObrazlozenjaZalbe createTipObrazlozenjaZalbe() {
        return new TipObrazlozenjaZalbe();
    }

    /**
     * Create an instance of {@link TipPoverenik }
     * 
     */
    public TipPoverenik createTipPoverenik() {
        return new TipPoverenik();
    }

    /**
     * Create an instance of {@link TipRazlogPodnosenjaZalbe }
     * 
     */
    public TipRazlogPodnosenjaZalbe createTipRazlogPodnosenjaZalbe() {
        return new TipRazlogPodnosenjaZalbe();
    }

    /**
     * Create an instance of {@link TipStaOptuzeniMoraDaUradi }
     * 
     */
    public TipStaOptuzeniMoraDaUradi createTipStaOptuzeniMoraDaUradi() {
        return new TipStaOptuzeniMoraDaUradi();
    }

    /**
     * Create an instance of {@link TipDogadjaj }
     * 
     */
    public TipDogadjaj createTipDogadjaj() {
        return new TipDogadjaj();
    }

    /**
     * Create an instance of {@link TipOptuzeni }
     * 
     */
    public TipOptuzeni createTipOptuzeni() {
        return new TipOptuzeni();
    }

    /**
     * Create an instance of {@link TipOdgovorNaDogadjaj }
     * 
     */
    public TipOdgovorNaDogadjaj createTipOdgovorNaDogadjaj() {
        return new TipOdgovorNaDogadjaj();
    }

    /**
     * Create an instance of {@link TipTrazenjeOdgovoraOdStraneOptuzenog }
     * 
     */
    public TipTrazenjeOdgovoraOdStraneOptuzenog createTipTrazenjeOdgovoraOdStraneOptuzenog() {
        return new TipTrazenjeOdgovoraOdStraneOptuzenog();
    }

    /**
     * Create an instance of {@link TipPrekrsaj }
     * 
     */
    public TipPrekrsaj createTipPrekrsaj() {
        return new TipPrekrsaj();
    }

    /**
     * Create an instance of {@link TipUpustvo }
     * 
     */
    public TipUpustvo createTipUpustvo() {
        return new TipUpustvo();
    }

    /**
     * Create an instance of {@link TipStaSeTrazilo }
     * 
     */
    public TipStaSeTrazilo createTipStaSeTrazilo() {
        return new TipStaSeTrazilo();
    }

    /**
     * Create an instance of {@link TipRazlogZahtevaZaInformacijeOdJavnogZnacaja.Informacija }
     * 
     */
    public TipRazlogZahtevaZaInformacijeOdJavnogZnacaja.Informacija createTipRazlogZahtevaZaInformacijeOdJavnogZnacajaInformacija() {
        return new TipRazlogZahtevaZaInformacijeOdJavnogZnacaja.Informacija();
    }

    /**
     * Create an instance of {@link TipZakon.BrojSl }
     * 
     */
    public TipZakon.BrojSl createTipZakonBrojSl() {
        return new TipZakon.BrojSl();
    }

    /**
     * Create an instance of {@link TipOperacijeKojeOptuzeniMoraDaIzvrsi.PrivatneInformacijeKojeOptuzeniMoraDaZastiti }
     * 
     */
    public TipOperacijeKojeOptuzeniMoraDaIzvrsi.PrivatneInformacijeKojeOptuzeniMoraDaZastiti createTipOperacijeKojeOptuzeniMoraDaIzvrsiPrivatneInformacijeKojeOptuzeniMoraDaZastiti() {
        return new TipOperacijeKojeOptuzeniMoraDaIzvrsi.PrivatneInformacijeKojeOptuzeniMoraDaZastiti();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_izvrsenja", scope = TipDogadjaj.class)
    public JAXBElement<String> createTipDogadjajDatumIzvrsenja(String value) {
        return new JAXBElement<String>(_TipDogadjajDatumIzvrsenja_QNAME, String.class, TipDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_podnetog_zahteva", scope = TipDogadjaj.class)
    public JAXBElement<String> createTipDogadjajDatumPodnetogZahteva(String value) {
        return new JAXBElement<String>(_TipDogadjajDatumPodnetogZahteva_QNAME, String.class, TipDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "zrtva", scope = TipDogadjaj.class)
    public JAXBElement<String> createTipDogadjajZrtva(String value) {
        return new JAXBElement<String>(_TipDogadjajZrtva_QNAME, String.class, TipDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipRazlogZahtevaZaInformacijeOdJavnogZnacaja }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "razlog_zahteva_za_informacije_od_javnog_znacaja", scope = TipDogadjaj.class)
    public JAXBElement<TipRazlogZahtevaZaInformacijeOdJavnogZnacaja> createTipDogadjajRazlogZahtevaZaInformacijeOdJavnogZnacaja(TipRazlogZahtevaZaInformacijeOdJavnogZnacaja value) {
        return new JAXBElement<TipRazlogZahtevaZaInformacijeOdJavnogZnacaja>(_TipDogadjajRazlogZahtevaZaInformacijeOdJavnogZnacaja_QNAME, TipRazlogZahtevaZaInformacijeOdJavnogZnacaja.class, TipDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_zahteva", scope = TipDogadjaj.class)
    public JAXBElement<String> createTipDogadjajDatumZahteva(String value) {
        return new JAXBElement<String>(_TipDogadjajDatumZahteva_QNAME, String.class, TipDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_obavestenja", scope = TipDogadjaj.class)
    public JAXBElement<String> createTipDogadjajDatumObavestenja(String value) {
        return new JAXBElement<String>(_TipDogadjajDatumObavestenja_QNAME, String.class, TipDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "izvrsenje_resenja", scope = TipDogadjaj.class)
    public JAXBElement<String> createTipDogadjajIzvrsenjeResenja(String value) {
        return new JAXBElement<String>(_TipDogadjajIzvrsenjeResenja_QNAME, String.class, TipDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipOptuzeni }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "optuzeni", scope = TipDogadjaj.class)
    public JAXBElement<TipOptuzeni> createTipDogadjajOptuzeni(TipOptuzeni value) {
        return new JAXBElement<TipOptuzeni>(_TipDogadjajOptuzeni_QNAME, TipOptuzeni.class, TipDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "ime_poverenika", scope = TipPoverenik.class)
    public JAXBElement<String> createTipPoverenikImePoverenika(String value) {
        return new JAXBElement<String>(_TipPoverenikImePoverenika_QNAME, String.class, TipPoverenik.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_odgovora_na_zalbu", scope = TipTrazenjeOdgovoraOdStraneOptuzenog.class)
    public JAXBElement<String> createTipTrazenjeOdgovoraOdStraneOptuzenogDatumOdgovoraNaZalbu(String value) {
        return new JAXBElement<String>(_TipTrazenjeOdgovoraOdStraneOptuzenogDatumOdgovoraNaZalbu_QNAME, String.class, TipTrazenjeOdgovoraOdStraneOptuzenog.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_akcije_poverenika", scope = TipTrazenjeOdgovoraOdStraneOptuzenog.class)
    public JAXBElement<String> createTipTrazenjeOdgovoraOdStraneOptuzenogDatumAkcijePoverenika(String value) {
        return new JAXBElement<String>(_TipTrazenjeOdgovoraOdStraneOptuzenogDatumAkcijePoverenika_QNAME, String.class, TipTrazenjeOdgovoraOdStraneOptuzenog.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipOptuzeni }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "optuzeni", scope = TipTrazenjeOdgovoraOdStraneOptuzenog.class)
    public JAXBElement<TipOptuzeni> createTipTrazenjeOdgovoraOdStraneOptuzenogOptuzeni(TipOptuzeni value) {
        return new JAXBElement<TipOptuzeni>(_TipDogadjajOptuzeni_QNAME, TipOptuzeni.class, TipTrazenjeOdgovoraOdStraneOptuzenog.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipStaSeTrazilo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "sta_se_trazilo", scope = TipTrazenjeOdgovoraOdStraneOptuzenog.class)
    public JAXBElement<TipStaSeTrazilo> createTipTrazenjeOdgovoraOdStraneOptuzenogStaSeTrazilo(TipStaSeTrazilo value) {
        return new JAXBElement<TipStaSeTrazilo>(_TipTrazenjeOdgovoraOdStraneOptuzenogStaSeTrazilo_QNAME, TipStaSeTrazilo.class, TipTrazenjeOdgovoraOdStraneOptuzenog.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipZakon }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "zakon", scope = TipTrazenjeOdgovoraOdStraneOptuzenog.class)
    public JAXBElement<TipZakon> createTipTrazenjeOdgovoraOdStraneOptuzenogZakon(TipZakon value) {
        return new JAXBElement<TipZakon>(_TipTrazenjeOdgovoraOdStraneOptuzenogZakon_QNAME, TipZakon.class, TipTrazenjeOdgovoraOdStraneOptuzenog.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "rok_za_pokretanje_upravnog_spora", scope = TipUpustvo.class)
    public JAXBElement<String> createTipUpustvoRokZaPokretanjeUpravnogSpora(String value) {
        return new JAXBElement<String>(_TipUpustvoRokZaPokretanjeUpravnogSpora_QNAME, String.class, TipUpustvo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "taksa_tuzbe", scope = TipUpustvo.class)
    public JAXBElement<String> createTipUpustvoTaksaTuzbe(String value) {
        return new JAXBElement<String>(_TipUpustvoTaksaTuzbe_QNAME, String.class, TipUpustvo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipZakon }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "zakon", scope = TipUpustvo.class)
    public JAXBElement<TipZakon> createTipUpustvoZakon(TipZakon value) {
        return new JAXBElement<TipZakon>(_TipTrazenjeOdgovoraOdStraneOptuzenogZakon_QNAME, TipZakon.class, TipUpustvo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "rok_trajanja_mora_izvrsi_resenje", scope = TipResenjeZalbe.class)
    public JAXBElement<String> createTipResenjeZalbeRokTrajanjaMoraIzvrsiResenje(String value) {
        return new JAXBElement<String>(_TipResenjeZalbeRokTrajanjaMoraIzvrsiResenje_QNAME, String.class, TipResenjeZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "zrtva", scope = TipResenjeZalbe.class)
    public JAXBElement<String> createTipResenjeZalbeZrtva(String value) {
        return new JAXBElement<String>(_TipDogadjajZrtva_QNAME, String.class, TipResenjeZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_podnetog_zahteva", scope = TipResenjeZalbe.class)
    public JAXBElement<String> createTipResenjeZalbeDatumPodnetogZahteva(String value) {
        return new JAXBElement<String>(_TipDogadjajDatumPodnetogZahteva_QNAME, String.class, TipResenjeZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "dokument_koji_se_trazi", scope = TipResenjeZalbe.class)
    public JAXBElement<String> createTipResenjeZalbeDokumentKojiSeTrazi(String value) {
        return new JAXBElement<String>(_TipResenjeZalbeDokumentKojiSeTrazi_QNAME, String.class, TipResenjeZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipOperacijeKojeOptuzeniMoraDaIzvrsi }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "operacije_koje_optuzeni_mora_da_izvrsi", scope = TipResenjeZalbe.class)
    public JAXBElement<TipOperacijeKojeOptuzeniMoraDaIzvrsi> createTipResenjeZalbeOperacijeKojeOptuzeniMoraDaIzvrsi(TipOperacijeKojeOptuzeniMoraDaIzvrsi value) {
        return new JAXBElement<TipOperacijeKojeOptuzeniMoraDaIzvrsi>(_TipResenjeZalbeOperacijeKojeOptuzeniMoraDaIzvrsi_QNAME, TipOperacijeKojeOptuzeniMoraDaIzvrsi.class, TipResenjeZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_obavestenja", scope = TipResenjeZalbe.class)
    public JAXBElement<String> createTipResenjeZalbeDatumObavestenja(String value) {
        return new JAXBElement<String>(_TipDogadjajDatumObavestenja_QNAME, String.class, TipResenjeZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_zahteva", scope = TipResenjeZalbe.class)
    public JAXBElement<String> createTipResenjeZalbeDatumZahteva(String value) {
        return new JAXBElement<String>(_TipDogadjajDatumZahteva_QNAME, String.class, TipResenjeZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipOptuzeni }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "optuzeni", scope = TipResenjeZalbe.class)
    public JAXBElement<TipOptuzeni> createTipResenjeZalbeOptuzeni(TipOptuzeni value) {
        return new JAXBElement<TipOptuzeni>(_TipDogadjajOptuzeni_QNAME, TipOptuzeni.class, TipResenjeZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "rok_trajanja_provera", scope = TipResenjeZalbe.class)
    public JAXBElement<String> createTipResenjeZalbeRokTrajanjaProvera(String value) {
        return new JAXBElement<String>(_TipResenjeZalbeRokTrajanjaProvera_QNAME, String.class, TipResenjeZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "zrtva", scope = TipOpisZalbe.class)
    public JAXBElement<String> createTipOpisZalbeZrtva(String value) {
        return new JAXBElement<String>(_TipDogadjajZrtva_QNAME, String.class, TipOpisZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_obavestenja", scope = TipOpisZalbe.class)
    public JAXBElement<String> createTipOpisZalbeDatumObavestenja(String value) {
        return new JAXBElement<String>(_TipDogadjajDatumObavestenja_QNAME, String.class, TipOpisZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_zahteva", scope = TipOpisZalbe.class)
    public JAXBElement<String> createTipOpisZalbeDatumZahteva(String value) {
        return new JAXBElement<String>(_TipDogadjajDatumZahteva_QNAME, String.class, TipOpisZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipOptuzeni }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "optuzeni", scope = TipOpisZalbe.class)
    public JAXBElement<TipOptuzeni> createTipOpisZalbeOptuzeni(TipOptuzeni value) {
        return new JAXBElement<TipOptuzeni>(_TipDogadjajOptuzeni_QNAME, TipOptuzeni.class, TipOpisZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_izbora", scope = TipOpisZalbe.class)
    public JAXBElement<String> createTipOpisZalbeDatumIzbora(String value) {
        return new JAXBElement<String>(_TipOpisZalbeDatumIzbora_QNAME, String.class, TipOpisZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "su.br.", scope = TipOpisZalbe.class)
    public JAXBElement<String> createTipOpisZalbeSuBr(String value) {
        return new JAXBElement<String>(_TipOpisZalbeSuBr_QNAME, String.class, TipOpisZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipZakon }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "zakon", scope = TipOpisZalbe.class)
    public JAXBElement<TipZakon> createTipOpisZalbeZakon(TipZakon value) {
        return new JAXBElement<TipZakon>(_TipTrazenjeOdgovoraOdStraneOptuzenogZakon_QNAME, TipZakon.class, TipOpisZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_pokretanja", scope = TipOpisZalbe.class)
    public JAXBElement<String> createTipOpisZalbeDatumPokretanja(String value) {
        return new JAXBElement<String>(_TipOpisZalbeDatumPokretanja_QNAME, String.class, TipOpisZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipRazlogZahtevaZaInformacijeOdJavnogZnacaja.Informacija }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "informacija", scope = TipRazlogZahtevaZaInformacijeOdJavnogZnacaja.class)
    public JAXBElement<TipRazlogZahtevaZaInformacijeOdJavnogZnacaja.Informacija> createTipRazlogZahtevaZaInformacijeOdJavnogZnacajaInformacija(TipRazlogZahtevaZaInformacijeOdJavnogZnacaja.Informacija value) {
        return new JAXBElement<TipRazlogZahtevaZaInformacijeOdJavnogZnacaja.Informacija>(_TipRazlogZahtevaZaInformacijeOdJavnogZnacajaInformacija_QNAME, TipRazlogZahtevaZaInformacijeOdJavnogZnacaja.Informacija.class, TipRazlogZahtevaZaInformacijeOdJavnogZnacaja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_izvrsenja", scope = TipOdgovorNaDogadjaj.class)
    public JAXBElement<String> createTipOdgovorNaDogadjajDatumIzvrsenja(String value) {
        return new JAXBElement<String>(_TipDogadjajDatumIzvrsenja_QNAME, String.class, TipOdgovorNaDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "lokacija_smrti", scope = TipOdgovorNaDogadjaj.class)
    public JAXBElement<String> createTipOdgovorNaDogadjajLokacijaSmrti(String value) {
        return new JAXBElement<String>(_TipOdgovorNaDogadjajLokacijaSmrti_QNAME, String.class, TipOdgovorNaDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_smrti_policija", scope = TipOdgovorNaDogadjaj.class)
    public JAXBElement<String> createTipOdgovorNaDogadjajDatumSmrtiPolicija(String value) {
        return new JAXBElement<String>(_TipOdgovorNaDogadjajDatumSmrtiPolicija_QNAME, String.class, TipOdgovorNaDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "rok_od_prijema_zahteva", scope = TipOdgovorNaDogadjaj.class)
    public JAXBElement<String> createTipOdgovorNaDogadjajRokOdPrijemaZahteva(String value) {
        return new JAXBElement<String>(_TipOdgovorNaDogadjajRokOdPrijemaZahteva_QNAME, String.class, TipOdgovorNaDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_obavestenja", scope = TipOdgovorNaDogadjaj.class)
    public JAXBElement<String> createTipOdgovorNaDogadjajDatumObavestenja(String value) {
        return new JAXBElement<String>(_TipDogadjajDatumObavestenja_QNAME, String.class, TipOdgovorNaDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_smrti", scope = TipOdgovorNaDogadjaj.class)
    public JAXBElement<String> createTipOdgovorNaDogadjajDatumSmrti(String value) {
        return new JAXBElement<String>(_TipOdgovorNaDogadjajDatumSmrti_QNAME, String.class, TipOdgovorNaDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "broj_obavestenja", scope = TipOdgovorNaDogadjaj.class)
    public JAXBElement<String> createTipOdgovorNaDogadjajBrojObavestenja(String value) {
        return new JAXBElement<String>(_TipOdgovorNaDogadjajBrojObavestenja_QNAME, String.class, TipOdgovorNaDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_izlaska_inspektora", scope = TipOdgovorNaDogadjaj.class)
    public JAXBElement<String> createTipOdgovorNaDogadjajDatumIzlaskaInspektora(String value) {
        return new JAXBElement<String>(_TipOdgovorNaDogadjajDatumIzlaskaInspektora_QNAME, String.class, TipOdgovorNaDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipZakon }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "zakon", scope = TipOdgovorNaDogadjaj.class)
    public JAXBElement<TipZakon> createTipOdgovorNaDogadjajZakon(TipZakon value) {
        return new JAXBElement<TipZakon>(_TipTrazenjeOdgovoraOdStraneOptuzenogZakon_QNAME, TipZakon.class, TipOdgovorNaDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "rok_o_obavestenju_da_li_poseduje_informacije", scope = TipOdgovorNaDogadjaj.class)
    public JAXBElement<String> createTipOdgovorNaDogadjajRokOObavestenjuDaLiPosedujeInformacije(String value) {
        return new JAXBElement<String>(_TipOdgovorNaDogadjajRokOObavestenjuDaLiPosedujeInformacije_QNAME, String.class, TipOdgovorNaDogadjaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "zrtva", scope = TipRazlogPodnosenjaZalbe.class)
    public JAXBElement<String> createTipRazlogPodnosenjaZalbeZrtva(String value) {
        return new JAXBElement<String>(_TipDogadjajZrtva_QNAME, String.class, TipRazlogPodnosenjaZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_obavestenja", scope = TipRazlogPodnosenjaZalbe.class)
    public JAXBElement<String> createTipRazlogPodnosenjaZalbeDatumObavestenja(String value) {
        return new JAXBElement<String>(_TipDogadjajDatumObavestenja_QNAME, String.class, TipRazlogPodnosenjaZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_zahteva", scope = TipRazlogPodnosenjaZalbe.class)
    public JAXBElement<String> createTipRazlogPodnosenjaZalbeDatumZahteva(String value) {
        return new JAXBElement<String>(_TipDogadjajDatumZahteva_QNAME, String.class, TipRazlogPodnosenjaZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipOptuzeni }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "optuzeni", scope = TipRazlogPodnosenjaZalbe.class)
    public JAXBElement<TipOptuzeni> createTipRazlogPodnosenjaZalbeOptuzeni(TipOptuzeni value) {
        return new JAXBElement<TipOptuzeni>(_TipDogadjajOptuzeni_QNAME, TipOptuzeni.class, TipRazlogPodnosenjaZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_do_kada_mora_da_se_izvrsi", scope = TipRazlogPodnosenjaZalbe.class)
    public JAXBElement<String> createTipRazlogPodnosenjaZalbeDatumDoKadaMoraDaSeIzvrsi(String value) {
        return new JAXBElement<String>(_TipRazlogPodnosenjaZalbeDatumDoKadaMoraDaSeIzvrsi_QNAME, String.class, TipRazlogPodnosenjaZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_zalbe", scope = TipRazlogPodnosenjaZalbe.class)
    public JAXBElement<String> createTipRazlogPodnosenjaZalbeDatumZalbe(String value) {
        return new JAXBElement<String>(_TipRazlogPodnosenjaZalbeDatumZalbe_QNAME, String.class, TipRazlogPodnosenjaZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipOperacijeKojeOptuzeniMoraDaIzvrsi.PrivatneInformacijeKojeOptuzeniMoraDaZastiti }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "privatne_informacije_koje_optuzeni_mora_da_zastiti", scope = TipOperacijeKojeOptuzeniMoraDaIzvrsi.class)
    public JAXBElement<TipOperacijeKojeOptuzeniMoraDaIzvrsi.PrivatneInformacijeKojeOptuzeniMoraDaZastiti> createTipOperacijeKojeOptuzeniMoraDaIzvrsiPrivatneInformacijeKojeOptuzeniMoraDaZastiti(TipOperacijeKojeOptuzeniMoraDaIzvrsi.PrivatneInformacijeKojeOptuzeniMoraDaZastiti value) {
        return new JAXBElement<TipOperacijeKojeOptuzeniMoraDaIzvrsi.PrivatneInformacijeKojeOptuzeniMoraDaZastiti>(_TipOperacijeKojeOptuzeniMoraDaIzvrsiPrivatneInformacijeKojeOptuzeniMoraDaZastiti_QNAME, TipOperacijeKojeOptuzeniMoraDaIzvrsi.PrivatneInformacijeKojeOptuzeniMoraDaZastiti.class, TipOperacijeKojeOptuzeniMoraDaIzvrsi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "fusnota", scope = Resenje.class)
    public JAXBElement<String> createResenjeFusnota(String value) {
        return new JAXBElement<String>(_ResenjeFusnota_QNAME, String.class, Resenje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipPoverenik }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "poverenik", scope = Resenje.class)
    public JAXBElement<TipPoverenik> createResenjePoverenik(TipPoverenik value) {
        return new JAXBElement<TipPoverenik>(_ResenjePoverenik_QNAME, TipPoverenik.class, Resenje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "podnaslov", scope = Resenje.class)
    public JAXBElement<String> createResenjePodnaslov(String value) {
        return new JAXBElement<String>(_ResenjePodnaslov_QNAME, String.class, Resenje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipResenjeZalbe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "resenje_zalbe", scope = Resenje.class)
    public JAXBElement<TipResenjeZalbe> createResenjeResenjeZalbe(TipResenjeZalbe value) {
        return new JAXBElement<TipResenjeZalbe>(_ResenjeResenjeZalbe_QNAME, TipResenjeZalbe.class, Resenje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "naslov", scope = Resenje.class)
    public JAXBElement<String> createResenjeNaslov(String value) {
        return new JAXBElement<String>(_ResenjeNaslov_QNAME, String.class, Resenje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipDesno }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "desno", scope = Resenje.class)
    public JAXBElement<TipDesno> createResenjeDesno(TipDesno value) {
        return new JAXBElement<TipDesno>(_ResenjeDesno_QNAME, TipDesno.class, Resenje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipLevo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "levo", scope = Resenje.class)
    public JAXBElement<TipLevo> createResenjeLevo(TipLevo value) {
        return new JAXBElement<TipLevo>(_ResenjeLevo_QNAME, TipLevo.class, Resenje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipObrazlozenjaZalbe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "obrazlozenja_zalbe", scope = Resenje.class)
    public JAXBElement<TipObrazlozenjaZalbe> createResenjeObrazlozenjaZalbe(TipObrazlozenjaZalbe value) {
        return new JAXBElement<TipObrazlozenjaZalbe>(_ResenjeObrazlozenjaZalbe_QNAME, TipObrazlozenjaZalbe.class, Resenje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipOpisZalbe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "opis_zalbe", scope = Resenje.class)
    public JAXBElement<TipOpisZalbe> createResenjeOpisZalbe(TipOpisZalbe value) {
        return new JAXBElement<TipOpisZalbe>(_ResenjeOpisZalbe_QNAME, TipOpisZalbe.class, Resenje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "clan", scope = TipZakon.class)
    public JAXBElement<String> createTipZakonClan(String value) {
        return new JAXBElement<String>(_TipZakonClan_QNAME, String.class, TipZakon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "naziv_zakona", scope = TipZakon.class)
    public JAXBElement<String> createTipZakonNazivZakona(String value) {
        return new JAXBElement<String>(_TipZakonNazivZakona_QNAME, String.class, TipZakon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "tacka", scope = TipZakon.class)
    public JAXBElement<String> createTipZakonTacka(String value) {
        return new JAXBElement<String>(_TipZakonTacka_QNAME, String.class, TipZakon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "naziv_sluzbenog_glasnika", scope = TipZakon.class)
    public JAXBElement<String> createTipZakonNazivSluzbenogGlasnika(String value) {
        return new JAXBElement<String>(_TipZakonNazivSluzbenogGlasnika_QNAME, String.class, TipZakon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "stav", scope = TipZakon.class)
    public JAXBElement<String> createTipZakonStav(String value) {
        return new JAXBElement<String>(_TipZakonStav_QNAME, String.class, TipZakon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipZakon.BrojSl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "broj_sl.", scope = TipZakon.class)
    public JAXBElement<TipZakon.BrojSl> createTipZakonBrojSl(TipZakon.BrojSl value) {
        return new JAXBElement<TipZakon.BrojSl>(_TipZakonBrojSl_QNAME, TipZakon.BrojSl.class, TipZakon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipZakon }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "zakon", scope = TipStaSeTrazilo.class)
    public JAXBElement<TipZakon> createTipStaSeTraziloZakon(TipZakon value) {
        return new JAXBElement<TipZakon>(_TipTrazenjeOdgovoraOdStraneOptuzenogZakon_QNAME, TipZakon.class, TipStaSeTrazilo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "sediste_optuzenog", scope = TipOptuzeni.class)
    public JAXBElement<String> createTipOptuzeniSedisteOptuzenog(String value) {
        return new JAXBElement<String>(_TipOptuzeniSedisteOptuzenog_QNAME, String.class, TipOptuzeni.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "broj_obavestenja", scope = TipOptuzeni.class)
    public JAXBElement<String> createTipOptuzeniBrojObavestenja(String value) {
        return new JAXBElement<String>(_TipOdgovorNaDogadjajBrojObavestenja_QNAME, String.class, TipOptuzeni.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "naziv_optuzenog", scope = TipOptuzeni.class)
    public JAXBElement<String> createTipOptuzeniNazivOptuzenog(String value) {
        return new JAXBElement<String>(_TipOptuzeniNazivOptuzenog_QNAME, String.class, TipOptuzeni.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipOptuzeni }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "optuzeni", scope = TipStaOptuzeniMoraDaUradi.class)
    public JAXBElement<TipOptuzeni> createTipStaOptuzeniMoraDaUradiOptuzeni(TipOptuzeni value) {
        return new JAXBElement<TipOptuzeni>(_TipDogadjajOptuzeni_QNAME, TipOptuzeni.class, TipStaOptuzeniMoraDaUradi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipZakon }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "zakon", scope = TipStaOptuzeniMoraDaUradi.class)
    public JAXBElement<TipZakon> createTipStaOptuzeniMoraDaUradiZakon(TipZakon value) {
        return new JAXBElement<TipZakon>(_TipTrazenjeOdgovoraOdStraneOptuzenogZakon_QNAME, TipZakon.class, TipStaOptuzeniMoraDaUradi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_izvrsenja", scope = TipPrekrsaj.class)
    public JAXBElement<String> createTipPrekrsajDatumIzvrsenja(String value) {
        return new JAXBElement<String>(_TipDogadjajDatumIzvrsenja_QNAME, String.class, TipPrekrsaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_obavestenja", scope = TipPrekrsaj.class)
    public JAXBElement<String> createTipPrekrsajDatumObavestenja(String value) {
        return new JAXBElement<String>(_TipDogadjajDatumObavestenja_QNAME, String.class, TipPrekrsaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "broj_obavestenja", scope = TipPrekrsaj.class)
    public JAXBElement<String> createTipPrekrsajBrojObavestenja(String value) {
        return new JAXBElement<String>(_TipOdgovorNaDogadjajBrojObavestenja_QNAME, String.class, TipPrekrsaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "datum_izlaska_inspektora", scope = TipPrekrsaj.class)
    public JAXBElement<String> createTipPrekrsajDatumIzlaskaInspektora(String value) {
        return new JAXBElement<String>(_TipOdgovorNaDogadjajDatumIzlaskaInspektora_QNAME, String.class, TipPrekrsaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipZakon }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/resenja", name = "zakon", scope = TipPrekrsaj.class)
    public JAXBElement<TipZakon> createTipPrekrsajZakon(TipZakon value) {
        return new JAXBElement<TipZakon>(_TipTrazenjeOdgovoraOdStraneOptuzenogZakon_QNAME, TipZakon.class, TipPrekrsaj.class, value);
    }

}
