//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.27 at 10:25:37 AM CET 
//


package com.poverenik.poverenik.model.resenja;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipObrazlozenja_zalbe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipObrazlozenja_zalbe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="razlog_podnosenja_zalbe" type="{http://www.ftn.uns.ac.rs/resenja}TipRazlogPodnosenjaZalbe"/>
 *         &lt;element name="trazenje_odgovora_od_strane_optuzenog" type="{http://www.ftn.uns.ac.rs/resenja}TipTrazenjeOdgovoraOdStraneOptuzenog"/>
 *         &lt;element name="odluka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dogadjaj" type="{http://www.ftn.uns.ac.rs/resenja}TipDogadjaj"/>
 *         &lt;element name="odgovor_na_dogadjaj" type="{http://www.ftn.uns.ac.rs/resenja}TipOdgovorNaDogadjaj"/>
 *         &lt;element name="prekrsaj" type="{http://www.ftn.uns.ac.rs/resenja}TipPrekrsaj" minOccurs="0"/>
 *         &lt;element name="sta_optuzeni_mora_da_uradi" type="{http://www.ftn.uns.ac.rs/resenja}TipStaOptuzeniMoraDaUradi" minOccurs="0"/>
 *         &lt;element name="upustvo" type="{http://www.ftn.uns.ac.rs/resenja}TipUpustvo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipObrazlozenja_zalbe", propOrder = {
    "razlogPodnosenjaZalbe",
    "trazenjeOdgovoraOdStraneOptuzenog",
    "odluka",
    "dogadjaj",
    "odgovorNaDogadjaj",
    "prekrsaj",
    "staOptuzeniMoraDaUradi",
    "upustvo"
})
public class TipObrazlozenjaZalbe {

    @XmlElement(name = "razlog_podnosenja_zalbe", required = true)
    protected TipRazlogPodnosenjaZalbe razlogPodnosenjaZalbe;
    @XmlElement(name = "trazenje_odgovora_od_strane_optuzenog", required = true)
    protected TipTrazenjeOdgovoraOdStraneOptuzenog trazenjeOdgovoraOdStraneOptuzenog;
    @XmlElement(required = true)
    protected String odluka;
    @XmlElement(required = true)
    protected TipDogadjaj dogadjaj;
    @XmlElement(name = "odgovor_na_dogadjaj", required = true)
    protected TipOdgovorNaDogadjaj odgovorNaDogadjaj;
    protected TipPrekrsaj prekrsaj;
    @XmlElement(name = "sta_optuzeni_mora_da_uradi")
    protected TipStaOptuzeniMoraDaUradi staOptuzeniMoraDaUradi;
    protected TipUpustvo upustvo;

    /**
     * Gets the value of the razlogPodnosenjaZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link TipRazlogPodnosenjaZalbe }
     *     
     */
    public TipRazlogPodnosenjaZalbe getRazlogPodnosenjaZalbe() {
        return razlogPodnosenjaZalbe;
    }

    /**
     * Sets the value of the razlogPodnosenjaZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipRazlogPodnosenjaZalbe }
     *     
     */
    public void setRazlogPodnosenjaZalbe(TipRazlogPodnosenjaZalbe value) {
        this.razlogPodnosenjaZalbe = value;
    }

    /**
     * Gets the value of the trazenjeOdgovoraOdStraneOptuzenog property.
     * 
     * @return
     *     possible object is
     *     {@link TipTrazenjeOdgovoraOdStraneOptuzenog }
     *     
     */
    public TipTrazenjeOdgovoraOdStraneOptuzenog getTrazenjeOdgovoraOdStraneOptuzenog() {
        return trazenjeOdgovoraOdStraneOptuzenog;
    }

    /**
     * Sets the value of the trazenjeOdgovoraOdStraneOptuzenog property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipTrazenjeOdgovoraOdStraneOptuzenog }
     *     
     */
    public void setTrazenjeOdgovoraOdStraneOptuzenog(TipTrazenjeOdgovoraOdStraneOptuzenog value) {
        this.trazenjeOdgovoraOdStraneOptuzenog = value;
    }

    /**
     * Gets the value of the odluka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOdluka() {
        return odluka;
    }

    /**
     * Sets the value of the odluka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOdluka(String value) {
        this.odluka = value;
    }

    /**
     * Gets the value of the dogadjaj property.
     * 
     * @return
     *     possible object is
     *     {@link TipDogadjaj }
     *     
     */
    public TipDogadjaj getDogadjaj() {
        return dogadjaj;
    }

    /**
     * Sets the value of the dogadjaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipDogadjaj }
     *     
     */
    public void setDogadjaj(TipDogadjaj value) {
        this.dogadjaj = value;
    }

    /**
     * Gets the value of the odgovorNaDogadjaj property.
     * 
     * @return
     *     possible object is
     *     {@link TipOdgovorNaDogadjaj }
     *     
     */
    public TipOdgovorNaDogadjaj getOdgovorNaDogadjaj() {
        return odgovorNaDogadjaj;
    }

    /**
     * Sets the value of the odgovorNaDogadjaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipOdgovorNaDogadjaj }
     *     
     */
    public void setOdgovorNaDogadjaj(TipOdgovorNaDogadjaj value) {
        this.odgovorNaDogadjaj = value;
    }

    /**
     * Gets the value of the prekrsaj property.
     * 
     * @return
     *     possible object is
     *     {@link TipPrekrsaj }
     *     
     */
    public TipPrekrsaj getPrekrsaj() {
        return prekrsaj;
    }

    /**
     * Sets the value of the prekrsaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipPrekrsaj }
     *     
     */
    public void setPrekrsaj(TipPrekrsaj value) {
        this.prekrsaj = value;
    }

    /**
     * Gets the value of the staOptuzeniMoraDaUradi property.
     * 
     * @return
     *     possible object is
     *     {@link TipStaOptuzeniMoraDaUradi }
     *     
     */
    public TipStaOptuzeniMoraDaUradi getStaOptuzeniMoraDaUradi() {
        return staOptuzeniMoraDaUradi;
    }

    /**
     * Sets the value of the staOptuzeniMoraDaUradi property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipStaOptuzeniMoraDaUradi }
     *     
     */
    public void setStaOptuzeniMoraDaUradi(TipStaOptuzeniMoraDaUradi value) {
        this.staOptuzeniMoraDaUradi = value;
    }

    /**
     * Gets the value of the upustvo property.
     * 
     * @return
     *     possible object is
     *     {@link TipUpustvo }
     *     
     */
    public TipUpustvo getUpustvo() {
        return upustvo;
    }

    /**
     * Sets the value of the upustvo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipUpustvo }
     *     
     */
    public void setUpustvo(TipUpustvo value) {
        this.upustvo = value;
    }

}
