//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.08 at 03:09:37 AM CET 
//


package parser.obavestenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for tipUvid complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tipUvid">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="godina" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
 *         &lt;element name="opis_trazene_informacije" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ime_dana">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Ponedeljak"/>
 *               &lt;enumeration value="Utorak"/>
 *               &lt;enumeration value="Sreda"/>
 *               &lt;enumeration value="\u010cetvrtak"/>
 *               &lt;enumeration value="Petak"/>
 *               &lt;enumeration value="Subota"/>
 *               &lt;enumeration value="Nedelja"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="broj_sati">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="8"/>
 *               &lt;maxInclusive value="21"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="pocetak_akcije">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}time">
 *               &lt;minInclusive value="08:00:00"/>
 *               &lt;maxInclusive value="20:00:00"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="kraj_akcije">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}time">
 *               &lt;minInclusive value="09:00:00"/>
 *               &lt;maxInclusive value="21:00:00"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="naziv_zgrade" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="naziv_ulice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="broj_ulice" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="broj_kancelarije" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tipUvid", propOrder = {
    "godina",
    "opisTrazeneInformacije",
    "imeDana",
    "brojSati",
    "pocetakAkcije",
    "krajAkcije",
    "nazivZgrade",
    "nazivUlice",
    "brojUlice",
    "brojKancelarije"
})
public class TipUvid {

    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar godina;
    @XmlElement(name = "opis_trazene_informacije", required = true)
    protected String opisTrazeneInformacije;
    @XmlElement(name = "ime_dana", required = true, nillable = true)
    protected String imeDana;
    @XmlElement(name = "broj_sati", required = true, type = Integer.class, nillable = true)
    protected Integer brojSati;
    @XmlElement(name = "pocetak_akcije", required = true, nillable = true)
    protected XMLGregorianCalendar pocetakAkcije;
    @XmlElement(name = "kraj_akcije", required = true, nillable = true)
    protected XMLGregorianCalendar krajAkcije;
    @XmlElement(name = "naziv_zgrade", required = true)
    protected String nazivZgrade;
    @XmlElement(name = "naziv_ulice", required = true)
    protected String nazivUlice;
    @XmlElement(name = "broj_ulice", required = true, type = Integer.class, nillable = true)
    protected Integer brojUlice;
    @XmlElement(name = "broj_kancelarije", required = true, type = Integer.class, nillable = true)
    protected Integer brojKancelarije;

    /**
     * Gets the value of the godina property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGodina() {
        return godina;
    }

    /**
     * Sets the value of the godina property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGodina(XMLGregorianCalendar value) {
        this.godina = value;
    }

    /**
     * Gets the value of the opisTrazeneInformacije property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpisTrazeneInformacije() {
        return opisTrazeneInformacije;
    }

    /**
     * Sets the value of the opisTrazeneInformacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpisTrazeneInformacije(String value) {
        this.opisTrazeneInformacije = value;
    }

    /**
     * Gets the value of the imeDana property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImeDana() {
        return imeDana;
    }

    /**
     * Sets the value of the imeDana property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImeDana(String value) {
        this.imeDana = value;
    }

    /**
     * Gets the value of the brojSati property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBrojSati() {
        return brojSati;
    }

    /**
     * Sets the value of the brojSati property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBrojSati(Integer value) {
        this.brojSati = value;
    }

    /**
     * Gets the value of the pocetakAkcije property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPocetakAkcije() {
        return pocetakAkcije;
    }

    /**
     * Sets the value of the pocetakAkcije property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPocetakAkcije(XMLGregorianCalendar value) {
        this.pocetakAkcije = value;
    }

    /**
     * Gets the value of the krajAkcije property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getKrajAkcije() {
        return krajAkcije;
    }

    /**
     * Sets the value of the krajAkcije property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setKrajAkcije(XMLGregorianCalendar value) {
        this.krajAkcije = value;
    }

    /**
     * Gets the value of the nazivZgrade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivZgrade() {
        return nazivZgrade;
    }

    /**
     * Sets the value of the nazivZgrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivZgrade(String value) {
        this.nazivZgrade = value;
    }

    /**
     * Gets the value of the nazivUlice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivUlice() {
        return nazivUlice;
    }

    /**
     * Sets the value of the nazivUlice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivUlice(String value) {
        this.nazivUlice = value;
    }

    /**
     * Gets the value of the brojUlice property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBrojUlice() {
        return brojUlice;
    }

    /**
     * Sets the value of the brojUlice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBrojUlice(Integer value) {
        this.brojUlice = value;
    }

    /**
     * Gets the value of the brojKancelarije property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBrojKancelarije() {
        return brojKancelarije;
    }

    /**
     * Sets the value of the brojKancelarije property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBrojKancelarije(Integer value) {
        this.brojKancelarije = value;
    }

}
